### ISSUE TITLE
Reverse Bytes : where is the "0"

### ISSUE THREAD

**Issue by cedeps** [RobTillaart/bitHelpers#6]
Hello and first of all thank you for Bithelpers!

I have a wiegand 26 rfid reader which gives me the card code.

I used the following code with
#include <bitHelpers.h>
#include <Wiegand.h>

```
void loop () {
if (wg.available ())
{
     uint16_t x = wg.getCode ();
  x = byteReverse (x);
  Serial.print ("Wiegand Original HEX =");
  Serial.println (wg.getCode (), HEX);
  Serial.print ("Reverse Hex =");
  Serial.println (x, HEX);
  
}
}
```

For a test with a **classic mifare** card I have:
Wiegand Original HEX = 9B**3FAA**
Reverse Hex = **AA3F**

The reverse function seems to work on 16 bits.

When I use an **ultralight mifare card** I have this answer:
Wiegand Original HEX = **5D95**04
Reverse Hex = 495

The "0" of the "**04**" seems to have disappeared.

Is this normal? I would like to have 0495 directly because it is impossible for me to know with the wiegand reader (or I do not know how to do it) if the RFID scan is done on a classic or ultralight mifare card ... (for example add "0" if ultralight ...)

**### 2nd question:**

There is a function for uint16 (2 bytes) or unit32 (4 bytes), but the wiegand outputs are 24 ... is it possible to have reverse on 3 bytes?

Thank you in advance for the time taken to read this message,
Cordially
Ced

**Comment by RobTillaart** [comment]
Hi 
Try to change
```uint16_t x = wg.getCode ();```

In
```uint32_t x = wg.getCode ();```

Does that help?

**Comment by RobTillaart** [comment]
Will think about the 24 bit reversal tomorrow.

**Comment by cedeps** [comment]
thank you for your reply. With uint32, the result is the same. the 0 is absent before the 4 ...

**Comment by RobTillaart** [comment]
I will investigate more this week.

**Comment by RobTillaart** [comment]
OK, some deeper analysis

> Wiegand Original HEX = 9B3FAA
Reverse Hex = AA3F
The reverse function seems to work on 16 bits.

The **byteReverse()** function is overloaded and how it works depends on its parameter. 

in your code you assign the Wiegand code to a 16 bit integer. 
```cpp
     uint16_t x = wg.getCode ();
  x = byteReverse (x);
```
As the Wiegand code is 24 bit, 8 bits are lost already in this assignment. 
The call to **byteReverse()** gets this 16 bit value as parameter and therefor only reverses 16 bits (2 bytes)

----

> When I use an ultralight mifare card I have this answer:
Wiegand Original HEX = 5D9504
Reverse Hex = 495
The "0" of the "04" seems to have disappeared.

This is an artefact of the Arduino **print()** function, it will skip leading zeros. 

A quick solution might be using these print functions  (and using uint32_t for the Wiegart code)
```cpp

void printHex16(uint16_t x)
{
  if (x < 0x1000) Serial.print('0');
  if (x < 0x100)  Serial.print('0');
  if (x < 0x10)   Serial.print('0');
  Serial.println(x, HEX);
}

void printHex24(uint32_t x)
{
  if (x < 0x100000)  Serial.print('0');
  if (x < 0x10000)   Serial.print('0');
  if (x < 0x1000) Serial.print('0');
  if (x < 0x100)  Serial.print('0');
  if (x < 0x10)   Serial.print('0');
  Serial.println(x, HEX);
}

void printHex32(uint32_t x)
{
  if (x < 0x10000000) Serial.print('0');
  if (x < 0x1000000) Serial.print('0');
  if (x < 0x100000)  Serial.print('0');
  if (x < 0x10000)   Serial.print('0');
  if (x < 0x1000) Serial.print('0');
  if (x < 0x100)  Serial.print('0');
  if (x < 0x10)   Serial.print('0');
  Serial.println(x, HEX);
}
```
(functions not tested, but you should get the idea)

These functions could be merged into one function ```void printHex(uint32_t value, uint8_t bytes)```. 

Might be an idea to add these to my https://github.com/RobTillaart/printHelpers class

**Comment by RobTillaart** [comment]
What you can do to reverse the 3 byte value and print it..

```cpp
void loop ()
{
  if (wg.available ())
  {
    uint32_t x = wg.getCode ();    // 24 bit fits in 32
    x = byteReverse (x);           // reverse 4 bytes
    x = x >> 8;                    // remove the 8 extra bits

    Serial.print ("Wiegand Original HEX =");
    printHex24(wg.getCode() );            
    Serial.print ("Reverse Hex =");
    printHex24(wg.getCode() );  
  }
}
```

**Comment by RobTillaart** [comment]
```cpp
void printHex(uint32_t x, uint8_t digits)
{
  uint32_t mask = 1ULL << (digits - 1) * 4;
  while (x < mask)
  {
    Serial.print('0');
    mask >>= 4;
  }
  Serial.print(x, HEX);
}
```

call : ```printHex( wg.getCode(), 6);```

**Comment by cedeps** [comment]
**SOLUTION**
Hello,
Thank you for your suggestions, both work perfectly.

I just **replaced** in the original code : `printHex (wg.getCode (), 6)`; with `printHex (x, 6)`;
(same in the first version `printHex24 (wg.getCode ());`>` printHex24 (x);`

For more clarity, I am sending you all of the 2 codes for my case, if it can be useful for others.

**Arduino library**
BitHelpers (of course!)
Wiegand: [https://github.com/monkeyboard/Wiegand-Protocol-Library-for-Arduino](url)

**Code 1:** for  WEMOS D1 mini ESP 32
```
#include <bitHelpers.h>
#include <Wiegand.h>

WIEGAND wg;


void setup() {
  Serial.begin(115200);  
  
  // default Wiegand Pin 2 and Pin 3 see image on README.md
  // for non UNO board, use wg.begin(pinD0, pinD1) where pinD0 and pinD1 
  // are the pins connected to D0 and D1 of wiegand reader respectively.
  wg.begin(26,25);
}

void loop() {
  if (wg.available ())
  {
    uint32_t x = wg.getCode ();    // 24 bit fits in 32
    x = byteReverse (x);           // reverse 4 bytes
    x = x >> 8;                    // remove the 8 extra bits
     printHex24(x);
     }
}

void printHex24(uint32_t x)
{
  if (x < 0x100000)  Serial.print('0');
  if (x < 0x10000)   Serial.print('0');
  if (x < 0x1000) Serial.print('0');
  if (x < 0x100)  Serial.print('0');
  if (x < 0x10)   Serial.print('0');
  Serial.print(x, HEX);
}
```
**Code 2:** for  WEMOS D1 mini ESP 32
```
#include <bitHelpers.h>
#include <Wiegand.h>

WIEGAND wg;


void setup() {
  Serial.begin(115200);  
  
  // default Wiegand Pin 2 and Pin 3 see image on README.md
  // for non UNO board, use wg.begin(pinD0, pinD1) where pinD0 and pinD1 
  // are the pins connected to D0 and D1 of wiegand reader respectively.
  wg.begin(26,25);
}

void loop() {
  if (wg.available ())
  {
   uint32_t x = wg.getCode ();    // 24 bit fits in 32
    x = byteReverse (x);           // reverse 4 bytes
    x = x >> 8;                    // remove the 8 extra bits
    printHex( x, 6);
     }
}

void printHex(uint32_t x, uint8_t digits)
{
  uint32_t mask = 1ULL << (digits - 1) * 4;
  while (x < mask)
  {
    Serial.print('0');
    mask >>= 4;
  }
  Serial.print(x, HEX);
}
```

Thank you again for your help,
Ced

**Comment by RobTillaart** [comment]
@cedeps 
Good to hear it solved the issue.
Please note I added  cpp after the backquotes in your post (2x) to get cpp syntax highlighting.
